#
#spring:
#  main:
#    web-application-type: servlet
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/customer
#    username: redakriate
#    password: reda12
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
server:
  port: 8080
  error:
    include-message: always
spring:
  main:
     web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: redakriate
    password: reda12
  jpa:
      hibernate:
         ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true