apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      hostNetwork: true
      containers:
        - name: springapp
          image: redakriate/spring-app:latest
          ports:
            - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30103

      