server:
  port: 8081
  error:
    include-message: always
cors:
  allowed-methods: "*"
  allowed-origins: "*"
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: redakriate
    password: redareda
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true