name : CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: redakriate
          POSTGRES_PASSWORD: redareda
          POSTGRES_DB: customer
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build et run Unit/Integration tests with maven
        run: mvn -ntp -B verify
      - name: l'envoie de notification
        run: curl -X POST -H '${{secrets.CONTENT_TYPE_SLACK}}' --data '{"text":"Workflow CI est terminée avec succés"}' ${{secrets.SLACK_URL}}